exam_tools/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import static_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'exam_tools.views.home', name='home'),
    # url(r'^exam_tools/', include('exam_tools.foo.urls')),

    url(r'^/?$', static_views.render_page, {'p' : 'pages/home.html'}, name='home'),
    url(r'^exam/', include('ipho_exam.urls', namespace='exam')),
    url(r'^poll/', include('ipho_poll.urls', namespace='poll')),
    url(r'^marking/', include('ipho_marking.urls', namespace='marking')),
    url(r'^print/', include('ipho_print.urls', namespace='print')),
    url(r'^downloads/', include('ipho_download.urls', namespace='download')),

    url(r'^accounts/login/?$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/?$', 'django.contrib.auth.views.logout', {'next_page':'/'}),
    url(r'^accounts/autologin/(?P<token>[0-9a-z\-]+)/?$', 'ipho_core.views.autologin', name='autologin'),
    url(r'^accounts/impersonate$', 'ipho_core.views.list_impersonate', name='impersonate'),

    url(r'^api/exam/', include('ipho_exam.urls_api', namespace='api-exam')),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

ipho_exam/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url


urlpatterns = patterns('ipho_exam.views',

    url(r'^/?$', 'index', name='index'),
    url(r'^wizard$', 'wizard', name='wizard'),
    url(r'^main$', 'main', name='main'),

    url(r'^translation/list/?$', 'translations_list', name='list'),
    url(r'^translation/add/(?P<exam_id>\d+)$', 'add_translation', name='add-translation'),
    url(r'^translation/upload/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'add_pdf_node', name='upload-translation'),
    url(r'^translation/export/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'translation_export', name='export-translation'),
    url(r'^translation/export/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)', 'translation_export', name='export-translation-version'),
    url(r'^translation/import/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'translation_import', name='import-translation'),
    url(r'^translation/import/confirm/(?P<slug>[0-9a-z\-]+)$', 'translation_import_confirm', name='import-translation-confirm'),
    url(r'^translation/all/?$', 'list_all_translations', name='list-all'),

    url(r'^languages/?$', 'list_language', name='language-list'),
    url(r'^languages/add$', 'add_language', name='language-add'),
    url(r'^languages/edit/(?P<lang_id>\d+)$', 'edit_language', name='language-edit'),

    url(r'^time$', 'time_response', name='time'),

    url(r'^editor/?$', 'editor'),
    url(r'^editor/(?P<exam_id>\d+)$', 'editor', name='editor-exam'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)$', 'editor', name='editor-question'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig/(?P<orig_id>\d+)$', 'editor', name='editor-orig'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig/(?P<orig_id>\d+)/lang/(?P<lang_id>\d+)?$', 'editor', name='editor-orig-lang'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig_diff/(?P<orig_id>\d+)v(?P<orig_diff>\d+)$', 'editor', name='editor-origdiff'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig_diff/(?P<orig_id>\d+)v(?P<orig_diff>\d+)/lang/(?P<lang_id>\d+)?$', 'editor', name='editor-origdiff-lang'),

    url(r'^pdf/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question', name='pdf'),
    url(r'^pdf/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question', name='pdf-version'),
    url(r'^tex/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question', {'raw_tex': True}, name='tex'),
    url(r'^tex/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question', {'raw_tex': True}, name='tex-version'),
    url(r'^odt/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question_odt', name='odt'),
    url(r'^html/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'compiled_question_html', name='html'),
    url(r'^html/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question_html', name='html-version'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_for_student', name='pdf-exam-student'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student',  {'type': 'P'}, name='pdf-exam-pos-student'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)/status$', 'pdf_exam_pos_student_status', name='pdf-exam-pos-student-status'),
    url(r'^scan/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student', {'type': 'S'}, name='scan-exam-pos-student'),
    url(r'^scan_orig/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student', {'type': 'O'}, name='scan-orig-exam-pos-student'),
    url(r'^print/(?P<type>\w)/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)/queue/(?P<queue>.+)$', 'print_doc', name='print-doc'),

    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)$', 'pdf_task', name='pdf-task'),
    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)/status$', 'task_status', name='pdf-task-status'),
    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)/log$', 'task_log', name='pdf-task-log'),

    url(r'^feedbacks/list/?$', 'feedbacks_list', name='feedbacks-list'),
    url(r'^feedbacks/add/(?P<exam_id>\d+)$', 'feedbacks_add', name='feedbacks-add'),
    url(r'^feedbacks/(?P<status>(U|L))/(?P<feedback_id>\d+)$', 'feedback_like', name='feedback-like'),
    url(r'^feedbacks/(?P<feedback_id>\d+)/status/(?P<status>\w)$', 'feedback_set_status', name='feedback-set-status'),

    url(r'^submission/list$', 'submission_exam_list', name='submission-exam-list'),
    url(r'^submission/(?P<exam_id>\d+)/assign$', 'submission_exam_assign', name='submission-exam-assign'),
    url(r'^submission/(?P<exam_id>\d+)/confirm$', 'submission_exam_confirm', name='submission-exam-confirm'),
    url(r'^submission/(?P<exam_id>\d+)/submitted$', 'submission_exam_submitted', name='submission-exam-submitted'),
    url(r'^submission/(?P<exam_id>\d+)/summary$', 'submission_summary', name='submission-summary'),

    url(r'^figures/?$', 'figure_list', name='figures'),
    url(r'^figure/add$', 'figure_add', name='figure-add'),
    url(r'^figure/(?P<fig_id>\d+)$', 'figure_edit', name='figure-edit'),
    url(r'^figure/(?P<fig_id>\d+)/remove$', 'figure_delete', name='figure-delete'),
    url(r'^figure/(?P<fig_id>\d+)/export$', 'figure_export', name='figure-export'),
    url(r'^figure/(?P<fig_id>\d+)/(?P<lang_id>\d+)/export$', 'figure_export', name='figure-lang-export'),

    url(r'^admin/?$', 'admin_list', name='admin'),
    url(r'^admin/(?P<exam_id>\d+)/quesiton/add$', 'admin_add_question', name='admin-add-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/question/delete$', 'admin_delete_question', name='admin-delete-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/question/edit$', 'admin_edit_question', name='admin-edit-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/newversion$', 'admin_new_version', name='admin-new-version'),
    url(r'^admin/(?P<question_id>\d+)/import$', 'admin_import_version', name='admin-import-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/delete$', 'admin_delete_version', name='admin-delete-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/accept$', 'admin_accept_version', name='admin-accept-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/publish$', 'admin_publish_version', name='admin-publish-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/settag$', 'admin_settag_version', name='admin-settag-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<compare_version>\d+)/v(?P<version_num>\d+)/accept$', 'admin_accept_version', name='admin-accept-version-diff'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor$', 'admin_editor', name='admin-editor'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/edit/(?P<block_id>\w+)$', 'admin_editor_block', name='admin-editor-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/delete/(?P<block_id>\w+)$', 'admin_editor_delete_block', name='admin-editor-delete-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/add/(?P<block_id>\w+)/(?P<tag_name>\w+)$', 'admin_editor_add_block', name='admin-editor-add-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/add/(?P<block_id>\w+)/(?P<after_id>\w+)/(?P<tag_name>\w+)$', 'admin_editor_add_block', name='admin-editor-add-block-after'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/moveup/(?P<parent_id>\w+)/(?P<block_id>\w+)$', 'admin_editor_move_block', {'direction': 'up'}, name='admin-editor-moveup-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/movedown/(?P<parent_id>\w+)/(?P<block_id>\w+)$', 'admin_editor_move_block', {'direction': 'down'}, name='admin-editor-movedown-block'),

    url(r'^admin/feedbacks/export$', 'feedbacks_export', name='admin-feedbacks-export-main'),
    url(r'^admin/feedbacks/export/E(?P<exam_id>\d+)_(?P<question_id>\d+).csv$', 'feedbacks_export_csv', name='admin-feedbacks-export-csv'),

    url(r'^admin/submissions/list/(?P<exam_id>\d+)$', 'admin_submission_list', name='admin-submission-list'),
    url(r'^admin/submissions/assign/(?P<exam_id>\d+)$', 'admin_submission_assign', name='admin-submission-assign'),
    url(r'^admin/submissions/(?P<submission_id>\d+)/delete$', 'admin_submission_delete', name='admin-submission-delete'),

    url(r'^admin/bulk-print/?$', 'bulk_print', name='bulk-print'),
    url(r'^admin/extra-sheets/?$', 'extra_sheets', name='extra-sheets-select-exam'),
    url(r'^admin/extra-sheets/(?P<exam_id>\d+)$', 'extra_sheets', name='extra-sheets'),
    url(r'^admin/scan-status/(?P<doc_id>\d+)/(?P<status>\w)$', 'set_scan_status', name='set-scan-status'),

ipho_poll/models.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.utils import timezone
from django.db import models
from ipho_core.models import Delegation
from django.contrib.auth.models import User
from django.db.models import Q, Count
from itertools import chain

from ipho_exam.models import Feedback

class QuestionManager(models.Manager):
    def is_draft(self):
        queryset = Question.objects.filter(end_date__isnull = True)
        return queryset
    def is_open(self):
        queryset = Question.objects.filter(end_date__gt = timezone.now)
        return queryset
    def is_closed(self):
        queryset = Question.objects.filter(end_date__lte = timezone.now)
        return queryset
    def not_voted_upon_by(self, user):
        user_tot_votes = user.votingright_set.all().count()
        qNotFull = Question.objects.is_open().filter(vote__voting_right__user=user).annotate(user_votes=Count('vote')).filter(user_votes__lt=user_tot_votes)
        qNoVotes = Question.objects.is_open().exclude(vote__voting_right__user=user)
        return list(chain(qNotFull, qNoVotes))



class Question(models.Model):
    class VOTE_RESULT_META:
        OPEN     = 0
        REJECTED = 1
        ACCEPTED = 2
        choices = (
            (OPEN,     'In progress'),
            (REJECTED, 'Rejected'),
            (ACCEPTED, 'Accepted'),
        )
    class IMPLEMENTATION_META:
        NOT_IMPL = 0
        IMPL     = 1
        choices = (
            (NOT_IMPL, 'Not implemented'),
            (IMPL,     'Implemented'),
        )


    title = models.CharField(max_length=200)
    content = models.TextField(blank=True, null=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    end_date = models.DateTimeField('end date', blank=True, null=True)
    vote_result = models.PositiveSmallIntegerField(choices=VOTE_RESULT_META.choices, default=VOTE_RESULT_META.OPEN)
    implementation = models.PositiveSmallIntegerField(choices=IMPLEMENTATION_META.choices, default=IMPLEMENTATION_META.NOT_IMPL)
    feedbacks = models.ManyToManyField(Feedback, blank=True, related_name='vote')
    objects = QuestionManager()
    def __str__(self):
        return self.title

    def is_draft(self):
        if not self.end_date:
            return True
        else:
            return False

    def is_open(self):
        if not self.is_draft() and not self.is_closed():
            return True
        else:
            return False

    def is_closed(self):
        if self.end_date:
            return self.end_date <= timezone.now()
        else:
            return False

    def choice_dict(self):
        choice_set = self.choice_set.all()
        choice_dict = {}
        for i,choice in enumerate(choice_set)   :
            choice_dict[choice] = chr(ord('A')+i)
        return choice_dict




class Choice(models.Model):
    question = models.ForeignKey(Question)
    label = models.CharField(max_length=3, blank=True, null=True)
    choice_text = models.CharField(max_length=200)
    def __str__(self):
        return '{}. {}'.format( self.label,self.choice_text)

    def calculateVotes(self):
        return Vote.objects.filter(choice = self).count()
    votes = property(calculateVotes)

    class Meta:
        ordering = ['label']

class VotingRight(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Vote(models.Model):
    question = models.ForeignKey(Question)
    choice = models.ForeignKey(Choice)
    voting_right = models.ForeignKey(VotingRight)

    def __str__(self):
        return self.choice.__str__()

    class Meta:
        unique_together = (('question', 'voting_right'))

templates/ipho_exam/panels/editor.html
<h2>Exam editor</h2>

<div class="panel-group" id="editor-accordion">
{% for ex in exam_list %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span class="glyphicon {% if forloop.first %}glyphicon-chevron-down{% else %}glyphicon-chevron-right{% endif %}"></span>
        <a data-toggle="collapse" data-parent="#editor-accordion" href="#editor-collapse-{{ forloop.counter }}">
          {{ ex.name }}
        </a>
      </h4>
    </div>
    <div id="editor-collapse-{{ forloop.counter }}" class="panel-collapse collapse {% if forloop.first %}in{% endif %}">
        <ul class="list-group">
        {% for q in ex.question_set.all %}
            <div class="dropdown">
                <a class="list-group-item dropdown-toggle" data-toggle="dropdown" href="#">
                    {{ q.name }} <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
                </a>
                <ul class="dropdown-menu">
                    {% for l in own_lang %}
                        <li><a href="{% url 'exam:editor-orig-lang' exam_id=ex.pk question_id=q.pk orig_id=1 lang_id=l.pk %}">{{ l.name }} <i class="fa fa-angle-double-right"></i></a></li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
        </ul>
    </div> <!-- ./panel-collapse -->
  </div> <!-- ./panel -->
{% endfor %}
</div>

templates/ipho_exam/panels/languages.html
{% load crispy_forms_tags %}

<h2>Languages</h2>

<div class="modal fade" id="language-modal" tabindex="-1">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
        <h4 class="modal-title"></h4>
      </div>
      <form method="post" action="">
          <div class="modal-body"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      </form>
    </div>
  </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Available languages</h3></div>
      <div id="language-list" class="list-group">
      {% for lang in own_lang %}
          <a class="list-group-item" data-toggle="modal" data-target="#language-modal" data-remote="false" href="{% url 'exam:language-edit' lang_id=lang.pk %}">{{ lang.name }} <span class="pull-right"><i class="fa fa-pencil"></i></span></a>
      {% empty %}
          <a class="list-group-item">No languages assigned to your delegation.</a>
      {% endfor %}
      </div>
</div>

<a class="btn btn-default" data-toggle="modal" data-target="#language-modal" data-remote="false" href="{% url 'exam:language-add' %}"><i class="fa fa-plus fa-fw"></i> Create new</a>

templates/ipho_exam/panels/submit.html
<h2>Final submit for printing</h2>
<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Open submissions</h3></div>
      <div id="language-list" class="list-group">
      {% for ex in exams_open %}
          <a class="list-group-item" href="{% url 'exam:submission-exam-assign' exam_id=ex.exam__pk %}">{{ ex.exam__name }} <span class="pull-right"><i class="fa fa-angle-double-right"></i></span></a>
      {% empty %}
          <a class="list-group-item">No open exam.</a>
      {% endfor %}
      </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Closed submissions</h3></div>
      <div id="language-list" class="list-group">
          {% for ex in exams_closed %}
          <a class="list-group-item" href="{% url 'exam:submission-exam-submitted' exam_id=ex.exam__pk %}">{{ ex.exam__name }} <span class="pull-right"><i class="fa fa-angle-double-right"></i></span></a>
      {% empty %}
          <a class="list-group-item">No closed exam.</a>
      {% endfor %}
      </div>
</div>

templates/ipho_exam/panels/view.html
<h2>View exams</h2>

<div class="panel-group" id="view-accordion">
{% for ex in exam_list %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span class="glyphicon {% if forloop.first %}glyphicon-chevron-down{% else %}glyphicon-chevron-right{% endif %}"></span>
        <a data-toggle="collapse" data-parent="#view-accordion" href="#view-collapse-{{ forloop.counter }}">
          {{ ex.name }}
        </a>
      </h4>
    </div>
    <div id="view-collapse-{{ forloop.counter }}" class="panel-collapse collapse {% if forloop.first %}in{% endif %}">
        <div class="list-group">
        {% for q in ex.question_set.all %}
            <div class="dropdown">
            <a class="list-group-item dropdown-toggle" data-toggle="dropdown" href="#">
                {{ q.name }} <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
            </a>
                <ul class="dropdown-menu">
                    {% for l in own_lang %}
                        <li><a href="{% url 'exam:pdf' question_id=q.pk lang_id=l.pk %}" target="_blank">{{ l.name }} <i class="fa fa-external-link" style="font-size:70%"></i></a></li>
                    {% endfor %}
                    {% if own_lang %}
                        <li class="divider"></li>
                    {% endif %}
                    {% for l in other_lang %}
                        <li><a href="{% url 'exam:pdf' question_id=q.pk lang_id=l.pk %}" target="_blank">{{ l.name }} ({{ l.delegation.country }}) <i class="fa fa-external-link" style="font-size:70%"></i></a></li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
        </div>
    </div> <!-- ./panel-collapse -->
  </div> <!-- ./panel -->
{% endfor %}
</div>