exam_tools/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import static_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'exam_tools.views.home', name='home'),
    # url(r'^exam_tools/', include('exam_tools.foo.urls')),

    url(r'^/?$', static_views.render_page, {'p' : 'pages/home.html'}, name='home'),
    url(r'^exam/', include('ipho_exam.urls', namespace='exam')),
    url(r'^poll/', include('ipho_poll.urls', namespace='poll')),
    url(r'^marking/', include('ipho_marking.urls', namespace='marking')),
    url(r'^print/', include('ipho_print.urls', namespace='print')),
    url(r'^downloads/', include('ipho_download.urls', namespace='download')),

    url(r'^accounts/login/?$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/?$', 'django.contrib.auth.views.logout', {'next_page':'/'}),
    url(r'^accounts/autologin/(?P<token>[0-9a-z\-]+)/?$', 'ipho_core.views.autologin', name='autologin'),
    url(r'^accounts/impersonate$', 'ipho_core.views.list_impersonate', name='impersonate'),

    url(r'^api/exam/', include('ipho_exam.urls_api', namespace='api-exam')),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

ipho_exam/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url


urlpatterns = patterns('ipho_exam.views',

    url(r'^/?$', 'index', name='index'),
    url(r'^wizard$', 'wizard', name='wizard'),
    url(r'^main$', 'main', name='main'),

    url(r'^translation/list/?$', 'translations_list', name='list'),
    url(r'^translation/add/(?P<exam_id>\d+)$', 'add_translation', name='add-translation'),
    url(r'^translation/upload/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'add_pdf_node', name='upload-translation'),
    url(r'^translation/export/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'translation_export', name='export-translation'),
    url(r'^translation/export/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)', 'translation_export', name='export-translation-version'),
    url(r'^translation/import/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'translation_import', name='import-translation'),
    url(r'^translation/import/confirm/(?P<slug>[0-9a-z\-]+)$', 'translation_import_confirm', name='import-translation-confirm'),
    url(r'^translation/all/?$', 'list_all_translations', name='list-all'),

    url(r'^languages/?$', 'list_language', name='language-list'),
    url(r'^languages/add$', 'add_language', name='language-add'),
    url(r'^languages/edit/(?P<lang_id>\d+)$', 'edit_language', name='language-edit'),

    url(r'^time$', 'time_response', name='time'),

    url(r'^editor/?$', 'editor'),
    url(r'^editor/(?P<exam_id>\d+)$', 'editor', name='editor-exam'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)$', 'editor', name='editor-question'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig/(?P<orig_id>\d+)$', 'editor', name='editor-orig'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig/(?P<orig_id>\d+)/lang/(?P<lang_id>\d+)?$', 'editor', name='editor-orig-lang'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig_diff/(?P<orig_id>\d+)v(?P<orig_diff>\d+)$', 'editor', name='editor-origdiff'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig_diff/(?P<orig_id>\d+)v(?P<orig_diff>\d+)/lang/(?P<lang_id>\d+)?$', 'editor', name='editor-origdiff-lang'),

    url(r'^pdf/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question', name='pdf'),
    url(r'^pdf/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question', name='pdf-version'),
    url(r'^tex/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question', {'raw_tex': True}, name='tex'),
    url(r'^tex/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question', {'raw_tex': True}, name='tex-version'),
    url(r'^odt/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question_odt', name='odt'),
    url(r'^html/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'compiled_question_html', name='html'),
    url(r'^html/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question_html', name='html-version'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_for_student', name='pdf-exam-student'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student',  {'type': 'P'}, name='pdf-exam-pos-student'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)/status$', 'pdf_exam_pos_student_status', name='pdf-exam-pos-student-status'),
    url(r'^scan/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student', {'type': 'S'}, name='scan-exam-pos-student'),
    url(r'^scan_orig/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student', {'type': 'O'}, name='scan-orig-exam-pos-student'),
    url(r'^print/(?P<type>\w)/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)/queue/(?P<queue>.+)$', 'print_doc', name='print-doc'),

    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)$', 'pdf_task', name='pdf-task'),
    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)/status$', 'task_status', name='pdf-task-status'),
    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)/log$', 'task_log', name='pdf-task-log'),

    url(r'^feedbacks/list/?$', 'feedbacks_list', name='feedbacks-list'),
    url(r'^feedbacks/add/(?P<exam_id>\d+)$', 'feedbacks_add', name='feedbacks-add'),
    url(r'^feedbacks/(?P<status>(U|L))/(?P<feedback_id>\d+)$', 'feedback_like', name='feedback-like'),
    url(r'^feedbacks/(?P<feedback_id>\d+)/status/(?P<status>\w)$', 'feedback_set_status', name='feedback-set-status'),

    url(r'^submission/list$', 'submission_exam_list', name='submission-exam-list'),
    url(r'^submission/(?P<exam_id>\d+)/assign$', 'submission_exam_assign', name='submission-exam-assign'),
    url(r'^submission/(?P<exam_id>\d+)/confirm$', 'submission_exam_confirm', name='submission-exam-confirm'),
    url(r'^submission/(?P<exam_id>\d+)/submitted$', 'submission_exam_submitted', name='submission-exam-submitted'),
    url(r'^submission/(?P<exam_id>\d+)/summary$', 'submission_summary', name='submission-summary'),

    url(r'^figures/?$', 'figure_list', name='figures'),
    url(r'^figure/add$', 'figure_add', name='figure-add'),
    url(r'^figure/(?P<fig_id>\d+)$', 'figure_edit', name='figure-edit'),
    url(r'^figure/(?P<fig_id>\d+)/remove$', 'figure_delete', name='figure-delete'),
    url(r'^figure/(?P<fig_id>\d+)/export$', 'figure_export', name='figure-export'),
    url(r'^figure/(?P<fig_id>\d+)/(?P<lang_id>\d+)/export$', 'figure_export', name='figure-lang-export'),

    url(r'^admin/?$', 'admin_list', name='admin'),
    url(r'^admin/(?P<exam_id>\d+)/quesiton/add$', 'admin_add_question', name='admin-add-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/question/delete$', 'admin_delete_question', name='admin-delete-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/question/edit$', 'admin_edit_question', name='admin-edit-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/newversion$', 'admin_new_version', name='admin-new-version'),
    url(r'^admin/(?P<question_id>\d+)/import$', 'admin_import_version', name='admin-import-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/delete$', 'admin_delete_version', name='admin-delete-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/accept$', 'admin_accept_version', name='admin-accept-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/publish$', 'admin_publish_version', name='admin-publish-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/settag$', 'admin_settag_version', name='admin-settag-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<compare_version>\d+)/v(?P<version_num>\d+)/accept$', 'admin_accept_version', name='admin-accept-version-diff'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor$', 'admin_editor', name='admin-editor'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/edit/(?P<block_id>\w+)$', 'admin_editor_block', name='admin-editor-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/delete/(?P<block_id>\w+)$', 'admin_editor_delete_block', name='admin-editor-delete-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/add/(?P<block_id>\w+)/(?P<tag_name>\w+)$', 'admin_editor_add_block', name='admin-editor-add-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/add/(?P<block_id>\w+)/(?P<after_id>\w+)/(?P<tag_name>\w+)$', 'admin_editor_add_block', name='admin-editor-add-block-after'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/moveup/(?P<parent_id>\w+)/(?P<block_id>\w+)$', 'admin_editor_move_block', {'direction': 'up'}, name='admin-editor-moveup-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/movedown/(?P<parent_id>\w+)/(?P<block_id>\w+)$', 'admin_editor_move_block', {'direction': 'down'}, name='admin-editor-movedown-block'),

    url(r'^admin/feedbacks/export$', 'feedbacks_export', name='admin-feedbacks-export-main'),
    url(r'^admin/feedbacks/export/E(?P<exam_id>\d+)_(?P<question_id>\d+).csv$', 'feedbacks_export_csv', name='admin-feedbacks-export-csv'),

    url(r'^admin/submissions/list/(?P<exam_id>\d+)$', 'admin_submission_list', name='admin-submission-list'),
    url(r'^admin/submissions/assign/(?P<exam_id>\d+)$', 'admin_submission_assign', name='admin-submission-assign'),
    url(r'^admin/submissions/(?P<submission_id>\d+)/delete$', 'admin_submission_delete', name='admin-submission-delete'),

    url(r'^admin/bulk-print/?$', 'bulk_print', name='bulk-print'),
    url(r'^admin/extra-sheets/?$', 'extra_sheets', name='extra-sheets-select-exam'),
    url(r'^admin/extra-sheets/(?P<exam_id>\d+)$', 'extra_sheets', name='extra-sheets'),
    url(r'^admin/scan-status/(?P<doc_id>\d+)/(?P<status>\w)$', 'set_scan_status', name='set-scan-status'),

ipho_marking/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url

from . import views

urlpatterns = [
## Delegation views
    url(r'^/?$', views.delegation_summary, name='delegation-summary'),
    url(r'^export/exam/(?P<exam_id>\d+)$', views.delegation_export, name='delegation-export'),
    url(r'^detail/(?P<stud_id>\d+)/question/(?P<question_id>\d+)$', views.delegation_stud_view, name='delegation-stud-detail'),
    url(r'^detail_all/question/(?P<question_id>\d+)$', views.delegation_view_all, name='delegation-all-detail'),
    url(r'^detail/(?P<stud_id>\d+)/question/(?P<question_id>\d+)/edit$', views.delegation_stud_edit, name='delegation-stud-detail-edit'),
    url(r'^detail_all/question/(?P<question_id>\d+)/edit$', views.delegation_edit_all, name='delegation-all-detail-edit'),
    url(r'^confirm/(?P<exam_id>\d+)$', views.delegation_confirm, name='delegation-confirm'),

## Markers
# TODO
## Moderations views
    url(r'^moderate/?$', views.moderation_index, name='moderation-index'),
    url(r'^moderate/question/(?P<question_id>\d+)$', views.moderation_index, name='moderation-index-question'),
    url(r'^moderate/question/(?P<question_id>\d+)/delegation/(?P<delegation_id>\d+)$', views.moderation_detail, name='moderation-detail'),
    url(r'^moderate/question/(?P<question_id>\d+)/delegation/(?P<delegation_id>\d+)/confirmed$', views.moderation_confirmed, name='moderation-confirmed'),

##  staff views
    url(r'^staff/import/?$', views.import_exam, name='import-exam'),
    url(r'^staff/?$', views.summary, name='summary'),
    url(r'^staff/v(?P<version>\w)/student/(?P<stud_id>\d+)/question/(?P<question_id>\d+)/edit$', views.staff_stud_detail, name='staff-stud-detail'),

    url(r'^all/export.csv$', views.export, name='export'),

    url(r'^submission/summary$', views.submission_summary, name='submission-summary'),
    url(r'^progress$', views.progress, name='progress'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Oly Exams Team">
    <meta name="google-site-verification" content="zqUrYerHwOScwmLIi5QyzGlA6gQn7DaG4idgsqq3_7U" />

	<link rel="apple-touch-icon" sizes="180x180" href="{% static "apple-touch-icon.png" %}">
	<link rel="icon" type="image/png" href="{% static "favicon-32x32.png" %}" sizes="32x32">
	<link rel="icon" type="image/png" href="{% static "favicon-16x16.png" %}" sizes="16x16">
	<link rel="manifest" href="{% static "manifest.json" %}">
	<link rel="mask-icon" href="{% static "safari-pinned-tab.svg" %}" color="#5bbad5">
	<meta name="theme-color" content="#ffffff">

    <title>{% block head-title %}Exam Tools{% endblock %}</title>

    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">

    {% block extra-head %}{% endblock %}

    <style>
    body {
      padding-top: 20px;
      padding-bottom: 20px;
    }
    </style>
  </head>

  <body>

      {% if DEMO_MODE %}
      <div class="alert alert-info" role="alert"><div class="container"><strong>DEMO VERSION.</strong> This is a demo version of the Exam Tools. (v{{ VERSION }} - {{ VERSION_DATE }})</div></div>
      {% endif %}
      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Exam Tools</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Exam <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  {% if perms.ipho_core.is_delegation %}
                  <li class="dropdown-header">Step-by-step guide</li>
                  <li><a href="{% url 'exam:wizard' %}">Get started!</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Translations</li>
                  <li><a href="{% url 'exam:language-list' %}">Define languages</a></li>
                  <li><a href="{% url 'exam:list' %}">Your translations</a></li>
                  <li><a href="{% url 'exam:submission-exam-list' %}">Final submission</a></li>
                  <li class="divider"></li>
                  {% endif %}
                  <li class="dropdown-header">All translations</li>
                  <li><a href="{% url 'exam:list-all' %}">View all translations</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Exam feedbacks</li>
                  <li><a href="{% url 'exam:feedbacks-list' %}">Submit feedbacks</a></li>
                </ul>
              </li>

              {% if perms.ipho_core.is_delegation %}
              <li><a href="{% url 'marking:delegation-summary' %}">Results</a></li>
              {% endif %}
              {% if perms.ipho_core.can_vote %}
              <li><a href="{% url 'poll:voterIndex' %}">Voting</a></li>
              {% endif %}
              <li><a href="{% url 'download:main' %}">Downloads</a></li>
              <li><a href="{% url 'print:main' %}">Print</a></li>

              {% if perms.ipho_core.is_staff or perms.ipho_core.is_marker or perms.ipho_core.is_printstaff %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin tools <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  {% if perms.ipho_core.is_staff %}
                  <li class="dropdown-header">Exam</li>
                  <li><a href="{% url 'exam:admin' %}">Exam management</a></li>
                  <li><a href="{% url 'exam:figures' %}">Figures management</a></li>
                  <li><a href="{% url 'exam:submission-summary' exam_id=0 %}">Submission summary</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Feedbacks</li>
                  <li><a href="{% url 'exam:admin-feedbacks-export-main' %}">Export feedbacks</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Voting</li>
                  <li><a href="{% url 'poll:staffIndex' %}">Voting management</a></li>
                  <li class="divider"></li>
                  {% endif %}
                  {% if perms.ipho_core.is_printstaff %}
                  <li class="dropdown-header">Printing</li>
                  <li><a href="{% url 'exam:bulk-print' %}">Bulk print</a></li>
                  <li><a href="{% url 'exam:upload-scan' %}">Upload scans</a></li>
                  <li><a href="{% url 'exam:extra-sheets-select-exam' %}">Generate extra sheets</a></li>
                  {% endif %}
                  {% if perms.ipho_core.is_staff %}
                  <li class="divider"></li>
                  <li class="dropdown-header">Documents API</li>
                  <li><a href="{% url 'exam:api-keys' %}">Get API Keys</a></li>
                  <li><a href="{% url 'api-exam:schema' %}">API schema</a></li>
                  {% endif %}
                  {% if perms.ipho_core.is_staff or perms.ipho_core.is_marker %}
                  <li class="divider"></li>
                  <li class="dropdown-header">Marking</li>
                  {% if perms.ipho_core.is_staff %}
                  <li><a href="{% url 'marking:import-exam' %}">Import exam</a></li>
                  <li><a href="{% url 'marking:submission-summary' %}">Submission summary</a></li>
                  {% endif %}
                  <li><a href="{% url 'marking:summary' %}">Summary</a></li>
                  <li><a href="{% url 'marking:moderation-index' %}">Moderation</a></li>
                  <li><a href="{% url 'marking:export' %}">Export markings</a></li>
                  <li><a href="{% url 'marking:progress' %}">Progress</a></li>
                  {% endif %}
                  {% if perms.ipho_core.is_staff %}
                  <li class="divider"></li>
                  <li class="dropdown-header">Django admin</li>
                  <li><a href="{% url 'admin:index' %}">Admin interface</a></li>
                  <li><a href="{% url 'admin:ipho_exam_examaction_changelist' %}?action__exact=T&amp;o=-5">Exam submissions</a></li>
                  <li><a href="{% url 'impersonate' %}">Impersonate delegation</a></li>
                  {% endif %}
                </ul>
              </li>
              {% endif %}

              <li><a href="{{ DOCS_URL }}">Documentation</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li class="navbar-text">{{ user.username }},
                <strong>
                {% if user.is_superuser %}
                admin
                {% elif perms.ipho_core.is_staff %}
                staff
                {% elif perms.ipho_core.is_delegation %}
                delegation
                {% elif perms.ipho_core.is_marker %}
                marker
                {% else %}
                user
                {% endif %}
                </strong></li>
              <li><a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'django.contrib.auth.views.login' %}?next=/">Login</a></li>
            {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container -->
      </div>


      {% block content %}{% endblock %}

      <div class="footer">
          <hr />
          <div class="container">
              <p class="text-muted">Copyright © 2014 - 2017 <a href="http://oly-exams.org/">Oly Exams Team</a>. Version {{ VERSION }} - {{ VERSION_DATE }}.</p>
          </div>
      </div>

    <script src="{% static "jquery/js/jquery-1.11.2.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "bootstrap-ckeditor-modal-fix.js" %}"></script>
    {% block extra-script %}{% endblock %}
  </body>
</html>

templates/base_ckeditor.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Test CKEditor</title>
        <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
        
        <link href="{% static "exam/exam.css" %}" rel="stylesheet">
        <link href="{% static "mathquill/mathquill.css" %}" rel="stylesheet">
        
    </head>
    <body>
        <textarea name="editor1" id="editor1">
      {% block content %}{% endblock %}
        </textarea>
        
        <script src="{% static "jquery/js/jquery-1.8.2.min.js" %}"></script>
        
        <script src="{% static "mathquill/mathquill.min.js" %}"></script>
        
        <script type="text/x-mathjax-config">
          MathJax.Hub.Config({   jax: 	["input/TeX", "output/HTML-CSS"],
          			 								tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
        </script>
        <script type="text/javascript"
          src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
        </script>
        
        <script>
        		CKEDITOR.plugins.addExternal( 'mathedit', '{% static "mathedit/" %}', 'plugin.js' );
        
            
            $(function(){
            	var newtext = $("#editor1").html().replace(/\$(.+?)\$/g, '<img src="http://latex.codecogs.com/svg.latex?$1" />');
            	$("#editor1").html(newtext);

							
							CKEDITOR.replace( 'editor1', {
							    extraPlugins: 'mathedit',
							    height : '600px',
							});
            });
            
        </script>
    </body>
</html>

templates/base_fullexam.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>{% block head-title %}Exam Layout{% endblock %}</title>

    <link href="{% static "exam/exam.css" %}" rel="stylesheet">
    
		<script type="text/x-mathjax-config">
		  MathJax.Hub.Config({   jax: 	["input/TeX", "output/HTML-CSS"],
		  			 								tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
		</script>
		<script type="text/javascript"
		  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
		</script>
  </head>

  <body>
      {% block content %}{% endblock %}
  </body>
</html>