exam_tools/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import static_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'exam_tools.views.home', name='home'),
    # url(r'^exam_tools/', include('exam_tools.foo.urls')),

    url(r'^/?$', static_views.render_page, {'p' : 'pages/home.html'}, name='home'),
    url(r'^exam/', include('ipho_exam.urls', namespace='exam')),
    url(r'^poll/', include('ipho_poll.urls', namespace='poll')),
    url(r'^marking/', include('ipho_marking.urls', namespace='marking')),
    url(r'^print/', include('ipho_print.urls', namespace='print')),
    url(r'^downloads/', include('ipho_download.urls', namespace='download')),

    url(r'^accounts/login/?$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/?$', 'django.contrib.auth.views.logout', {'next_page':'/'}),
    url(r'^accounts/autologin/(?P<token>[0-9a-z\-]+)/?$', 'ipho_core.views.autologin', name='autologin'),
    url(r'^accounts/impersonate$', 'ipho_core.views.list_impersonate', name='impersonate'),

    url(r'^api/exam/', include('ipho_exam.urls_api', namespace='api-exam')),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

ipho_exam/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2017 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url


urlpatterns = patterns('ipho_exam.views',

    url(r'^/?$', 'index', name='index'),
    url(r'^wizard$', 'wizard', name='wizard'),
    url(r'^main$', 'main', name='main'),

    url(r'^translation/list/?$', 'translations_list', name='list'),
    url(r'^translation/add/(?P<exam_id>\d+)$', 'add_translation', name='add-translation'),
    url(r'^translation/upload/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'add_pdf_node', name='upload-translation'),
    url(r'^translation/export/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'translation_export', name='export-translation'),
    url(r'^translation/export/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)', 'translation_export', name='export-translation-version'),
    url(r'^translation/import/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'translation_import', name='import-translation'),
    url(r'^translation/import/confirm/(?P<slug>[0-9a-z\-]+)$', 'translation_import_confirm', name='import-translation-confirm'),
    url(r'^translation/all/?$', 'list_all_translations', name='list-all'),

    url(r'^languages/?$', 'list_language', name='language-list'),
    url(r'^languages/add$', 'add_language', name='language-add'),
    url(r'^languages/edit/(?P<lang_id>\d+)$', 'edit_language', name='language-edit'),

    url(r'^time$', 'time_response', name='time'),

    url(r'^editor/?$', 'editor'),
    url(r'^editor/(?P<exam_id>\d+)$', 'editor', name='editor-exam'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)$', 'editor', name='editor-question'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig/(?P<orig_id>\d+)$', 'editor', name='editor-orig'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig/(?P<orig_id>\d+)/lang/(?P<lang_id>\d+)?$', 'editor', name='editor-orig-lang'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig_diff/(?P<orig_id>\d+)v(?P<orig_diff>\d+)$', 'editor', name='editor-origdiff'),
    url(r'^editor/(?P<exam_id>\d+)/question/(?P<question_id>\d+)/orig_diff/(?P<orig_id>\d+)v(?P<orig_diff>\d+)/lang/(?P<lang_id>\d+)?$', 'editor', name='editor-origdiff-lang'),

    url(r'^pdf/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question', name='pdf'),
    url(r'^pdf/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question', name='pdf-version'),
    url(r'^tex/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question', {'raw_tex': True}, name='tex'),
    url(r'^tex/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question', {'raw_tex': True}, name='tex-version'),
    url(r'^odt/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)?$', 'compiled_question_odt', name='odt'),
    url(r'^html/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)$', 'compiled_question_html', name='html'),
    url(r'^html/question/(?P<question_id>\d+)/lang/(?P<lang_id>\d+)/v(?P<version_num>\d+)$', 'compiled_question_html', name='html-version'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_for_student', name='pdf-exam-student'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student',  {'type': 'P'}, name='pdf-exam-pos-student'),
    url(r'^pdf/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)/status$', 'pdf_exam_pos_student_status', name='pdf-exam-pos-student-status'),
    url(r'^scan/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student', {'type': 'S'}, name='scan-exam-pos-student'),
    url(r'^scan_orig/exam/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)$', 'pdf_exam_pos_student', {'type': 'O'}, name='scan-orig-exam-pos-student'),
    url(r'^print/(?P<type>\w)/(?P<exam_id>\d+)/(?P<position>\d+)/student/(?P<student_id>\d+)/queue/(?P<queue>.+)$', 'print_doc', name='print-doc'),

    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)$', 'pdf_task', name='pdf-task'),
    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)/status$', 'task_status', name='pdf-task-status'),
    url(r'^pdf-task/(?P<token>[0-9a-z\-]+)/log$', 'task_log', name='pdf-task-log'),

    url(r'^feedbacks/list/?$', 'feedbacks_list', name='feedbacks-list'),
    url(r'^feedbacks/add/(?P<exam_id>\d+)$', 'feedbacks_add', name='feedbacks-add'),
    url(r'^feedbacks/(?P<status>(U|L))/(?P<feedback_id>\d+)$', 'feedback_like', name='feedback-like'),
    url(r'^feedbacks/(?P<feedback_id>\d+)/status/(?P<status>\w)$', 'feedback_set_status', name='feedback-set-status'),

    url(r'^submission/list$', 'submission_exam_list', name='submission-exam-list'),
    url(r'^submission/(?P<exam_id>\d+)/assign$', 'submission_exam_assign', name='submission-exam-assign'),
    url(r'^submission/(?P<exam_id>\d+)/confirm$', 'submission_exam_confirm', name='submission-exam-confirm'),
    url(r'^submission/(?P<exam_id>\d+)/submitted$', 'submission_exam_submitted', name='submission-exam-submitted'),
    url(r'^submission/(?P<exam_id>\d+)/summary$', 'submission_summary', name='submission-summary'),

    url(r'^figures/?$', 'figure_list', name='figures'),
    url(r'^figure/add$', 'figure_add', name='figure-add'),
    url(r'^figure/(?P<fig_id>\d+)$', 'figure_edit', name='figure-edit'),
    url(r'^figure/(?P<fig_id>\d+)/remove$', 'figure_delete', name='figure-delete'),
    url(r'^figure/(?P<fig_id>\d+)/export$', 'figure_export', name='figure-export'),
    url(r'^figure/(?P<fig_id>\d+)/(?P<lang_id>\d+)/export$', 'figure_export', name='figure-lang-export'),

    url(r'^admin/?$', 'admin_list', name='admin'),
    url(r'^admin/(?P<exam_id>\d+)/quesiton/add$', 'admin_add_question', name='admin-add-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/question/delete$', 'admin_delete_question', name='admin-delete-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/question/edit$', 'admin_edit_question', name='admin-edit-question'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/newversion$', 'admin_new_version', name='admin-new-version'),
    url(r'^admin/(?P<question_id>\d+)/import$', 'admin_import_version', name='admin-import-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/delete$', 'admin_delete_version', name='admin-delete-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/accept$', 'admin_accept_version', name='admin-accept-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/publish$', 'admin_publish_version', name='admin-publish-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/settag$', 'admin_settag_version', name='admin-settag-version'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<compare_version>\d+)/v(?P<version_num>\d+)/accept$', 'admin_accept_version', name='admin-accept-version-diff'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor$', 'admin_editor', name='admin-editor'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/edit/(?P<block_id>\w+)$', 'admin_editor_block', name='admin-editor-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/delete/(?P<block_id>\w+)$', 'admin_editor_delete_block', name='admin-editor-delete-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/add/(?P<block_id>\w+)/(?P<tag_name>\w+)$', 'admin_editor_add_block', name='admin-editor-add-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/add/(?P<block_id>\w+)/(?P<after_id>\w+)/(?P<tag_name>\w+)$', 'admin_editor_add_block', name='admin-editor-add-block-after'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/moveup/(?P<parent_id>\w+)/(?P<block_id>\w+)$', 'admin_editor_move_block', {'direction': 'up'}, name='admin-editor-moveup-block'),
    url(r'^admin/(?P<exam_id>\d+)/(?P<question_id>\d+)/v(?P<version_num>\d+)/editor/block/movedown/(?P<parent_id>\w+)/(?P<block_id>\w+)$', 'admin_editor_move_block', {'direction': 'down'}, name='admin-editor-movedown-block'),

    url(r'^admin/feedbacks/export$', 'feedbacks_export', name='admin-feedbacks-export-main'),
    url(r'^admin/feedbacks/export/E(?P<exam_id>\d+)_(?P<question_id>\d+).csv$', 'feedbacks_export_csv', name='admin-feedbacks-export-csv'),

    url(r'^admin/submissions/list/(?P<exam_id>\d+)$', 'admin_submission_list', name='admin-submission-list'),
    url(r'^admin/submissions/assign/(?P<exam_id>\d+)$', 'admin_submission_assign', name='admin-submission-assign'),
    url(r'^admin/submissions/(?P<submission_id>\d+)/delete$', 'admin_submission_delete', name='admin-submission-delete'),

    url(r'^admin/bulk-print/?$', 'bulk_print', name='bulk-print'),
    url(r'^admin/extra-sheets/?$', 'extra_sheets', name='extra-sheets-select-exam'),
    url(r'^admin/extra-sheets/(?P<exam_id>\d+)$', 'extra_sheets', name='extra-sheets'),
    url(r'^admin/scan-status/(?P<doc_id>\d+)/(?P<status>\w)$', 'set_scan_status', name='set-scan-status'),

templates/ipho_exam/admin_editor_field.html
{% for field in fields_set %}
<div id="{{ field.id }}-container">
  <div class="field-content">
      <div class="row">
          <div class="col-xs-12">
              {% if parent %}
              <div class="btn-group">
                <a href="{% url 'exam:admin-editor-moveup-block' question_id=question.pk exam_id=exam.pk parent_id=parent.id block_id=field.id version_num=node_version %}" data-action="move" data-block-id="{{ field.id }}" class="btn btn-default btn-xs"><i class="fa fa-arrow-up"></i></a>
                <a href="{% url 'exam:admin-editor-movedown-block' question_id=question.pk exam_id=exam.pk parent_id=parent.id block_id=field.id version_num=node_version %}" data-action="move" data-block-id="{{ field.id }}" class="btn btn-default btn-xs"><i class="fa fa-arrow-down"></i></a>
              </div>
              {% endif %}
              <span class="label label-info">{{ field.display_name }}</span>
              <span id="{{ field.id }}-attributes">
              {% include 'ipho_exam/partials/admin_editor_attributes.html' with attributes=field.attributes %}
              </span>
              <a class="btn btn-xs btn-default" title="Edit block" data-toggle="modal" data-target="#block-modal" data-block-id="{{ field.id }}" data-remote="false" href="{% url 'exam:admin-editor-block' question_id=question.pk exam_id=exam.pk block_id=field.id version_num=node_version %}"><i class="fa fa-pencil fa-fw"></i></a>
              <a class="btn btn-xs btn-danger" href="{% url 'exam:admin-editor-delete-block' question_id=question.pk exam_id=exam.pk block_id=field.id version_num=node_version %}" title="Delete block" data-toggle="modal" data-target="#delete-modal" data-block-id="{{ field.id }}" data-remote="false" data-block-id="{{ field.id }}"><i class="fa fa-trash-o fa-fw"></i></a>
              {% if field.description %} <p>{{ field.description }}</p> {% endif %}
          </div>
      </div>

      <div class="row">
          <div class="col-sm-12">
              {% if field.has_text %}
              <div class="question-content" id="{{ field.id }}-content">
                  {{ field.content_html|safe }}
              </div>
              {% endif %}
          </div>
      </div>

  {% if field.has_children %}
      <div class="row">
          <div class="col-xs-12 content-field-nested" id="{{ field.id }}-children">
              {% if field.children %}
                  {% include 'ipho_exam/admin_editor_field.html' with fields_set=field.children parent=field %}
              {% endif %}
          </div>
      </div>
      
      {% if not field.children %}
      <div class="row no-child-add">
          <div class="col-xs-12">
              <div class="dropdown">
                <a class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" title="New block">
                  <i class="fa fa-plus fa-fw"></i>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  {% for qtag, qname in qml_types %}
                      {% if qtag in field.valid_children %}
                          <li><a data-action="add-block" data-block-id="{{ field.id }}" href="{% url 'exam:admin-editor-add-block' question_id=question.pk exam_id=exam.pk version_num=node_version block_id=field.id tag_name=qtag %}">{{ qname }}</a></li>
                      {% endif %}
                  {% endfor %}
                </ul>
              </div>
          </div>
      </div>
      {% endif %}
  {% endif %}
  </div>

  {% if parent %}
  <div class="row">
      <div class="col-xs-12">
          <div class="dropdown">
            <a class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" title="New block">
              <i class="fa fa-plus fa-fw"></i>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              {% for qtag, qname in qml_types %}
                  {% if qtag in parent.valid_children %}
                    <li><a data-action="add-block" data-block-id="{{ parent.id }}"  data-after-id="{{ field.id }}" href="{% url 'exam:admin-editor-add-block-after' question_id=question.pk exam_id=exam.pk version_num=node_version block_id=parent.id tag_name=qtag after_id=field.id %}">{{ qname }}</a></li>
                  {% endif %}
              {% endfor %}
            </ul>
          </div>
      </div>
  </div>
  {% endif %}

</div>
{% endfor %}

templates/ipho_exam/admin_feedbacks_export.html
{% extends "ipho_exam/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra-head %}
{% endblock %}

{% block breadcrumb %}
<li><a href="#">Admin</a></li>
<li class="active">Export feedbacks</li>
{% endblock %}

{% block pageheader %}<h1>Export feedbacks</h1>{% endblock %}

{% block exam-content %}
<p class="lead">Select the question from which you want to export the feedbacks.</p>

<div class="row">
  {% regroup questions by exam as questions_list %}
  {% for exam_questions in questions_list %}
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>{{ exam_questions.grouper.name }}</h4>
      </div>
      <div class="list-group">
        {% for q in exam_questions.list %}
        <a class="list-group-item" href="{% url 'exam:admin-feedbacks-export-csv' exam_id=q.exam.pk question_id=q.pk %}">
          {{ q.name }}
          <span class="pull-right">
            <i class="fa fa-file-excel-o"></i>
            <i class="fa fa-chevron-right"></i>
          </span>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

{% block extra-script %}
{% endblock %}

templates/ipho_exam/bulk_print.html
{% extends "ipho_exam/base.html" %}
{% load static %}
{% load exam_utils_tags %}
{% load crispy_forms_tags %}

{% block extra-head %}
<style>
.div-inline{
    display:inline-block;
}
</style>
{% endblock %}

{% block breadcrumb %}
<li><a href="#">Admin</a></li>
<li class="active">Bulk print</li>
{% endblock %}

{% block pageheader %}<h1>Bulk print</h1>{% endblock %}

{% block exam-content %}
<p class="lead">
View and print individual documents, or select and print in bulk.
</p>
<p class="alert alert-info">
<i class="fa fa-info-circle"></i>
This list shows only documents that have been submitted by the delegations.
</p>

<div id="alerts-container">
{% for class, msg in messages %}
<div class="alert {{ class }} alert-dismissible"><button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>{{ msg|safe }}</div>
{% endfor %}
</div>

  <div>

      <div class="dropdown div-inline">
        <a class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
      {% if exam %}
          {{ exam.name }}
      {% else %}
          Filter exam
      {% endif %}
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% this_url ex=None page=1 %}">-- None --</a></li>
      {% for ex in exams %}
          <li {% if exam == ex %} class="active" {% endif %}><a href="{% this_url ex=ex.pk page=1 %}">{{ ex.name }}</a></li>
      {% endfor %}
        </ul>
      </div>

      <div class="dropdown div-inline">
        <a class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
      {% if delegation %}
          {{ delegation.name }}
      {% else %}
          Filter delegation
      {% endif %}
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% this_url dg=None page=1 %}">-- None --</a></li>
      {% for dg in delegations %}
          <li {% if delegation == dg %} class="active" {% endif %}><a href="{% this_url dg=dg.pk page=1 %}">{{ dg.country }} ({{ dg.name }})</a></li>
      {% endfor %}
        </ul>
      </div>

  </div>

    <form method="POST">
    <table class="table table-striped">
      <tr>
          <th>Exam</th>
          <th>#</th>
          <th>Student</th>
          <th>Num pages</th>
          <th>Barcode</th>
          <th>Printouts</th>
          <th>Scans</th>
          <th>Scan status</th>
          <th>Full scan</th>
      </tr>
      <tbody>
        {% for d in docs_list %}
          <tr>
            <td>{{ d.exam__name }}</td>
            <td>{{ d.position }}</td>
            <td>{{ d.student__code }}</td>
            <td>{{ d.num_pages }} / {{ d.barcode_num_pages }} / {{ d.extra_num_pages }}</td>
            <td>{{ d.barcode_base }}</td>
            <td align="center">
              <a class="btn btn-default btn-xs" href="{% url 'exam:pdf-exam-pos-student'  exam_id=d.exam__id student_id=d.student__id position=d.position %}"><i class="fa fa-fw fa-file-pdf-o"></i> view</a>
              <br />
              <input type="checkbox" name="printouts[]" value="{{ d.pk }}" />
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-print"></i>
                  print <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  {% for p in queue_list %}
                  <li><a href="{% url 'exam:print-doc' exam_id=d.exam__id position=d.position student_id=d.student__id queue=p.0 type='P' %}">{{ p.1 }}</a></li>
                  {% endfor %}
                </ul>
              </div>
              <br />
              {{ d.last_print_p|date:"SHORT_DATETIME_FORMAT" }}
            </td>
            <td align="center">
              {% if d.scan_file %}
                <a class="btn btn-default btn-xs" href="{% url 'exam:scan-exam-pos-student' exam_id=d.exam__id student_id=d.student__id position=d.position %}"><i class="fa fa-fw fa-file-pdf-o"></i> view</a>
                <br />
                <input type="checkbox" name="scans[]" value="{{ d.pk }}" />
                <div class="btn-group">
                  <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-print"></i>
                    print <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    {% for p in queue_list %}
                    <li><a href="{% url 'exam:print-doc' exam_id=d.exam__id position=d.position student_id=d.student__id queue=p.0 type='S' %}">{{ p.1 }}</a></li>
                    {% endfor %}
                  </ul>
                </div>
                <br />
                {{ d.last_print_s|date:"SHORT_DATETIME_FORMAT" }}
              {% endif %}
            </td>
            <td>
              {% if d.scan_file %}
              <div class="btn-group">
                {% for r,label in scan_status_choices %}
                <a class="btn btn-default btn-xs {% if d.scan_status == r %}active{% endif %}" href="{% url 'exam:set-scan-status' doc_id=d.pk status=r %}" title="{{ label }}" data-toggle="tooltip">{{ r }}</a>
                {% endfor %}
              </div>
                {% if d.scan_msg %}
                <br />
                <a href="#" data-toggle="popover" data-trigger="hover" data-html="true" data-container="body" data-content="{{ d.scan_msg }}"><span class="glyphicon glyphicon-info-sign"></span></a>
                {% endif %}
              {% endif %}
            </td>
            <td>
              {% if d.scan_file_orig %}
                <a class="btn btn-default btn-xs" href="{% url 'exam:scan-orig-exam-pos-student' exam_id=d.exam__id student_id=d.student__id position=d.position %}"><i class="fa fa-fw fa-file-pdf-o"></i> view</a>
                <br />
                <div class="btn-group">
                  <a class="btn btn-default btn-xs" href="{% url 'exam:set-scan-full'  doc_id=d.pk %}" title="set as default" data-toggle="tooltip"><i class="fa fa-fw fa-angle-double-left"></i></a>
                  <a class="btn btn-default btn-xs" href="#" title="evaluate codes" data-toggle="tooltip"><i class="fa fa-fw fa-qrcode"></i></a>
                </div>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% crispy form %}

    </form>

    <div class="text-center">
      <ul class="pagination">
        {% if docs_list.has_previous %}
        <li>
          <a href="{% this_url page=docs_list.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% else %}
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% endif %}
        {% for page in all_pages %}
        <li class="{% if page == docs_list.number %}active{% endif %}"><a href="{% this_url page=page %}">{{ page }}</a></li>
        {% endfor %}
        {% if docs_list.has_next %}
        <li>
          <a href="{% this_url page=docs_list.next_page_number %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% else %}
        <li class="disabled">
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

{% endblock %}

{% block extra-script %}
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
  $(function () {
  $('[data-toggle="popover"]').popover()
})
</script>
{% endblock %}